---
title: "Masters of Biostatistics"
output:
  distill::distill_article:
    toc: true
twitter:
  creator: "@JohnHelveston"
base_url: https://bokola214.netlify.app/
preview: images/owiti.png
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```

## 2020–21 academic year

```{r, echo=FALSE}
make_title_card(
    title = "3577: Linear Models",
    # text = "Spring 2021 | George Washington University",
    # subtext = "Foundations in exploring and visualizing data in R.",
    url = "https://www.uhasselt.be/"
    # image_src = "images/eda_hex_sticker_square.png",
    # image_width = 120
)

make_title_card(
    title = "3220: Concepts of Probability and Statistics",
    # text = "Spring 2021 | George Washington University",
    # subtext = "Foundations in exploring and visualizing data in R.",
    url = "https://www.uhasselt.be/"
    # image_src = "images/eda_hex_sticker_square.png",
    # image_width = 120
)

make_title_card(
    title = "3587: Programming in Python",
    # text = "Spring 2021 | George Washington University",
    # subtext = "Foundations in exploring and visualizing data in R.",
    url = "https://www.uhasselt.be/"
    # image_src = "images/eda_hex_sticker_square.png",
    # image_width = 120
)

make_title_card(
    title = "4432: Programming in R",
    # text = "Spring 2021 | George Washington University",
    # subtext = "Foundations in exploring and visualizing data in R.",
    url = "https://www.uhasselt.be/"
    # image_src = "images/eda_hex_sticker_square.png",
    # image_width = 120
)

make_title_card(
    title = "4431: Data Management",
    # text = "Spring 2021 | George Washington University",
    # subtext = "Foundations in exploring and visualizing data in R.",
    url = "https://www.uhasselt.be/"
    # image_src = "images/eda_hex_sticker_square.png",
    # image_width = 120
)
make_title_card(
    title = "1113: Project Learning from Data",
    # text = "Spring 2021 | George Washington University",
    # subtext = "Foundations in exploring and visualizing data in R.",
    url = "https://www.uhasselt.be/"
    # image_src = "images/eda_hex_sticker_square.png",
    # image_width = 120
)
```



